-- Retire the paise tag.
--
-- Now a no-op. It renamed flats.paise_tag to legacy_paise_tag, because the
-- column is UNIQUE with a CHECK and SQLite cannot drop such a column in place.
--
-- 0001 no longer creates that column at all, so on a fresh database there is
-- nothing here to rename. On the live database this migration is already
-- recorded and will never run again; the column was removed for real by
-- scripts/rebuild-flats.mjs, which lifts out every referencing row, rebuilds
-- the table, and puts them back with identical ids.
--
-- Kept as a file rather than deleted: removing it would renumber nothing but
-- would make d1_migrations reference a migration that no longer exists.
SELECT 1;
